
[assembly: SuppressMessage("Style", "IDE0305:Simplify collection initialization")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization")]
[assembly: SuppressMessage("Style", "IDE0301:Simplify collection initialization")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor")]
[assembly: SuppressMessage("Style", "IDE0300:Simplify collection initialization")]
[assembly: SuppressMessage("Roslynator", "RCS1139:Add summary element to documentation comment")]
[assembly: SuppressMessage("Roslynator", "RCS1214:Unnecessary interpolated string")]
[assembly: SuppressMessage("Roslynator", "RCS1163:Unused parameter")]
[assembly: SuppressMessage("Roslynator", "RCS1146:Use conditional access")]
